name: Ray's Blog for Software Developments
markdown: redcarpet
baseurl: '/articles'
theme: jekyll-theme-architect

---
layout: default
comments: true
permalink: /:title.html
---

collections:
  cookies: 
    output: true
    


