name: Ray's Blog for Software Developments
markdown: redcarpet
baseurl: '/articles'
theme: jekyll-theme-architect
permalink: /:title.html

---
layout: default
comments: true
---

collections:
  cookies: 
    output: true
    


