name: Written by Ray
markdown: redcarpet
baseurl: '/articles'
theme: jekyll-theme-architect

---
layout: default
comments: true
---

collections:
  cookies: 
    output: true
    permalink: /blog/:path/

permalink: /:title/
