name: Ray's Blog for Software Developments
markdown: redcarpet
baseurl: 'https://github.com/mania7539/articles'
theme: jekyll-theme-architect
permalink: /:title.html

---
layout: default
comments: true
---

collections:
  cookies: 
    output: true
    


