name: Architect Theme
markdown: redcarpet
baseurl: '/jekyll-architect-theme'
theme: jekyll-theme-architect

---
layout: default
comments: true
---

collections:
  cookies: 
    output: true
    permalink: /blog/:path/

permalink: /:title/
